/**
 * Seed: github_repositories
 * Loads sample GitHub repository records for local/testing use,
 * matching the GitHubRepository interface and github_repositories table.
 */

exports.seed = async function (knex) {
    // Clear existing rows before reseeding
    await knex('git_repos').del();

    await knex('git_repos').insert([
        {
            id: 401928374,
            node_id: 'R_kgDOGXaB1g',
            name: 'platform-core',
            full_name: 'intelliplatforms/platform-core',
            private: true,
            html_url: 'https://github.mycompany.com/intelliplatforms/platform-core',
            description: 'Core services and shared libraries for the platform.',
            fork: false,
            url: 'https://github.mycompany.com/api/v3/repos/intelliplatforms/platform-core',
            created_at: '2022-03-14T18:22:10Z',
            updated_at: '2026-09-15T09:41:03Z',
            pushed_at: '2026-09-16T21:07:44Z',
            git_url: 'git://github.mycompany.com/intelliplatforms/platform-core.git',
            ssh_url: 'git@github.mycompany.com:intelliplatforms/platform-core.git',
            clone_url: 'https://github.mycompany.com/intelliplatforms/platform-core.git',
            homepage: null,
            size: 184320,
            stargazers_count: 42,
            watchers_count: 42,
            language: 'TypeScript',
            forks_count: 3,
            archived: false,
            disabled: false,
            open_issues_count: 17,
            visibility: 'private',
            default_branch: 'main',
            topics: JSON.stringify(['backend', 'core', 'typescript']),
            allow_squash_merge: true,
            allow_merge_commit: false,
            allow_rebase_merge: true,
            delete_branch_on_merge: true,
        },
        {
            id: 401928501,
            node_id: 'R_kgDOGXaCFQ',
            name: 'infra-terraform',
            full_name: 'intelliplatforms/infra-terraform',
            private: true,
            html_url: 'https://github.mycompany.com/intelliplatforms/infra-terraform',
            description: 'Terraform modules for provisioning cloud infrastructure.',
            fork: false,
            url: 'https://github.mycompany.com/api/v3/repos/intelliplatforms/infra-terraform',
            created_at: '2021-11-02T14:05:51Z',
            updated_at: '2026-09-10T13:29:18Z',
            pushed_at: '2026-09-14T08:12:37Z',
            git_url: 'git://github.mycompany.com/intelliplatforms/infra-terraform.git',
            ssh_url: 'git@github.mycompany.com:intelliplatforms/infra-terraform.git',
            clone_url: 'https://github.mycompany.com/intelliplatforms/infra-terraform.git',
            homepage: null,
            size: 9840,
            stargazers_count: 15,
            watchers_count: 15,
            language: 'HCL',
            forks_count: 1,
            archived: false,
            disabled: false,
            open_issues_count: 4,
            visibility: 'internal',
            default_branch: 'main',
            topics: JSON.stringify(['terraform', 'infrastructure', 'devops']),
            allow_squash_merge: true,
            allow_merge_commit: true,
            allow_rebase_merge: false,
            delete_branch_on_merge: true,
        },
        {
            id: 512847293,
            node_id: 'R_kgDOHfM9PQ',
            name: 'neubird-ml-pipeline',
            full_name: 'neubird-ai/neubird-ml-pipeline',
            private: true,
            html_url: 'https://github.mycompany.com/neubird-ai/neubird-ml-pipeline',
            description: 'Model training and inference pipeline for incident classification.',
            fork: false,
            url: 'https://github.mycompany.com/api/v3/repos/neubird-ai/neubird-ml-pipeline',
            created_at: '2023-06-08T10:14:22Z',
            updated_at: '2026-09-17T02:18:56Z',
            pushed_at: '2026-09-17T11:03:29Z',
            git_url: 'git://github.mycompany.com/neubird-ai/neubird-ml-pipeline.git',
            ssh_url: 'git@github.mycompany.com:neubird-ai/neubird-ml-pipeline.git',
            clone_url: 'https://github.mycompany.com/neubird-ai/neubird-ml-pipeline.git',
            homepage: 'https://docs.neubird.internal/ml-pipeline',
            size: 62148,
            stargazers_count: 28,
            watchers_count: 28,
            language: 'Python',
            forks_count: 5,
            archived: false,
            disabled: false,
            open_issues_count: 9,
            visibility: 'private',
            default_branch: 'main',
            topics: JSON.stringify(['machine-learning', 'python', 'incident-detection']),
            allow_squash_merge: true,
            allow_merge_commit: false,
            allow_rebase_merge: true,
            delete_branch_on_merge: true,
        },
        {
            id: 512847410,
            node_id: 'R_kgDOHfM9sg',
            name: 'servicenow-connector',
            full_name: 'neubird-ai/servicenow-connector',
            private: true,
            html_url: 'https://github.mycompany.com/neubird-ai/servicenow-connector',
            description: 'Integration layer for ingesting and posting back to ServiceNow ITSM.',
            fork: false,
            url: 'https://github.mycompany.com/api/v3/repos/neubird-ai/servicenow-connector',
            created_at: '2023-09-19T16:40:03Z',
            updated_at: '2026-09-16T19:55:11Z',
            pushed_at: '2026-09-17T07:22:48Z',
            git_url: 'git://github.mycompany.com/neubird-ai/servicenow-connector.git',
            ssh_url: 'git@github.mycompany.com:neubird-ai/servicenow-connector.git',
            clone_url: 'https://github.mycompany.com/neubird-ai/servicenow-connector.git',
            homepage: null,
            size: 14872,
            stargazers_count: 11,
            watchers_count: 11,
            language: 'Go',
            forks_count: 2,
            archived: false,
            disabled: false,
            open_issues_count: 6,
            visibility: 'internal',
            default_branch: 'main',
            topics: JSON.stringify(['servicenow', 'integration', 'golang']),
            allow_squash_merge: true,
            allow_merge_commit: true,
            allow_rebase_merge: false,
            delete_branch_on_merge: true,
        },
        {
            id: 512847556,
            node_id: 'R_kgDOHfM-BA',
            name: 'alert-noise-classifier',
            full_name: 'neubird-ai/alert-noise-classifier',
            private: false,
            html_url: 'https://github.mycompany.com/neubird-ai/alert-noise-classifier',
            description: 'Lightweight rules + model ensemble for tagging alerts as signal vs. noise.',
            fork: false,
            url: 'https://github.mycompany.com/api/v3/repos/neubird-ai/alert-noise-classifier',
            created_at: '2024-01-25T08:51:40Z',
            updated_at: '2026-09-12T20:03:37Z',
            pushed_at: '2026-09-15T15:44:02Z',
            git_url: 'git://github.mycompany.com/neubird-ai/alert-noise-classifier.git',
            ssh_url: 'git@github.mycompany.com:neubird-ai/alert-noise-classifier.git',
            clone_url: 'https://github.mycompany.com/neubird-ai/alert-noise-classifier.git',
            homepage: null,
            size: 3204,
            stargazers_count: 67,
            watchers_count: 67,
            language: 'Python',
            forks_count: 8,
            archived: false,
            disabled: false,
            open_issues_count: 2,
            visibility: 'public',
            default_branch: 'main',
            topics: JSON.stringify(['alerting', 'noise-reduction', 'classification']),
            allow_squash_merge: true,
            allow_merge_commit: false,
            allow_rebase_merge: true,
            delete_branch_on_merge: true,
        },
    ]);
};